packages:
  - 'xmcl/packages/**'
  - 'xmcl-electron-app'
  - 'xmcl-runtime-api'
  - 'xmcl-runtime'
  - 'xmcl-keystone-ui'
  - 'starmade-launcher-ui'
  - 'xmcl-client-vue'
  - '.github/actions/*'
  - 'packages/**'
